export { default as TemplatePage } from "./Template";

export { default as AlienPage } from "./Alien";
export { default as AndyPage } from "./Andy";
export { default as BonesawPage } from "./Bonesaw";
export { default as ChallengePage } from "./Challenge";
// export { default as ChickenPage } from "./Chicken";
// export { default as DictionaryPage } from "./Dictionary";
// export { default as DoneskisPage } from "./Doneskis";
// export { default as DunListPage } from "./DunList";
// export { default as DunyunRingsPage } from "./DunyunRings";
// export { default as FacemanPage } from "./Faceman";
// export { default as FeatureSuggestionPage } from "./FeatureSuggestion";
// export { default as FishingWithDadPage } from "./FishingWithDad";
// export { default as FrenchPage } from "./French";
// export { default as HoroscopesPage } from "./Horoscopes";
// export { default as JillSandwichPage } from "./JillSandwich";
// export { default as LiterallyRatchetPage } from "./LiterallyRatchet";
// export { default as MoneyPage } from "./Money";
// export { default as PresidentialSlogansPage } from "./PresidentialSlogans";
// export { default as RiddlePage } from "./Riddle";
// export { default as RipoffPage } from "./Ripoff";
// export { default as SatanClausPage } from "./SatanClaus";
// export { default as SongLyricsPage } from "./SongLyrics";
// export { default as SpoopyPage } from "./SpoopyPage";
// export { default as VladimirSnootinPage } from "./VladimirSnootin";
